### ISSUE TITLE
如何运行起来

### ISSUE THREAD

**Issue by zhaotao666** [zhangyaqi1989/Gcode-Reader#2]
主程序怎么写？您能告诉我下吗

**Comment by zhangyaqi1989** [comment]
You can use the below command to see help.
`python src/gcode_reader.py -h`
For example, the below command can plot the whole octopus part located at gcode/fdm_regular/octo.gcode
`python src/gcode_reader.py -t 1 gcode/fdm_regular/octo.gcode -p`

**Comment by zhangyaqi1989** [comment]
Some example gcode files are in the gcode folder. You can put the gcode file anywhere you like.
