### ISSUE TITLE
Error when trying to plot a file

### ISSUE THREAD

**Issue by onekk** [zhangyaqi1989/Gcode-Reader#3]
`
Gcode Reader
1. Line segments information: 
count    33292.000000
mean         2.425849
std          9.927422
min          0.020000
25%          0.329844
50%          0.420001
75%          0.604308
max         90.112000
dtype: float64
2. Number of layers: 207
Traceback (most recent call last):
  File "gcode_reader.py", line 1001, in <module>
    command_line_runner()
  File "gcode_reader.py", line 935, in command_line_runner
    gcode_reader.describe()
  File "gcode_reader.py", line 800, in describe
    df = pd.DataFrame(data)
  File "/usr/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 365, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length

`

with your code latticebunny it works, but with latticebunyy-50 this error are raised:

`
Gcode Reader
gcode_reader.py:786: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  series = pd.Series(self.lengths)
1. Line segments information: 
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
2. Number of layers: 0
Traceback (most recent call last):
  File "gcode_reader.py", line 1001, in <module>
    command_line_runner()
  File "gcode_reader.py", line 935, in command_line_runner
    gcode_reader.describe()
  File "gcode_reader.py", line 791, in describe
    self._compute_subpaths()
  File "gcode_reader.py", line 507, in _compute_subpaths
    x0, y0, x1, y1, z = self.segs[0, :]
IndexError: too many indices for array

`

I'm using artix linux (arch linux)

Regards

Carlo D.

**Comment by zhangyaqi1989** [comment]
Could you share the file you plot?

**Comment by onekk** [comment]
Yes but it is 1.7mb long, it is  generated with Slic3r  1.3.1 dev. and it prints.

how to share the file?


Regards

Carlo D.

**Comment by zhangyaqi1989** [comment]
The latticebunny-50 is a scode file, which is designed for my research on powder bed fusion simulation. I put it in the wrong folder. I have moved it to the right folder (you need to pull the update). In order to plot it, type 4 should be used. The below command works on my machine.

`python gcode_reader.py -t 4 ../gcode/scode-lpbf/latticebunny-50.scode -p`

**Comment by zhangyaqi1989** [comment]
> Yes but it is 1.7mb long, it is generated with Slic3r 1.3.1 dev. and it prints.
> 
> how to share the file?
> 
> Regards
> 
> Carlo D.

If you do not mind, you can email the gcode file to me. My email address is zhangyaqi1989@gmail.com.

**Comment by onekk** [comment]
Done, hope it will help

Regards

Carlo D.

**Comment by zhangyaqi1989** [comment]
I have fixed it. The reason why it did not work is because there are lift/restore z commands in the G-code. However when I implemented the code, I assumed z can only increase. Now it should work.

**Comment by onekk** [comment]
Yes, they are the moves for the anti-oozing system, it optionally raise the nozzle, retract the filament, go to next position, lower the nozzle and the advance the filament for the new prints.

Many Thanks

Carlo D.

**Comment by onekk** [comment]
Hi, the file I send you seems to plot correctly, but, now I've another problem.

I'm developing a little python program to write gcode files, for 3d printing, so I've to test the creation methods, the files are pretty easy.

`
 Created by fdmcode
; File   : ./file.gcode 
; Date   : 2020-05-20 10:51:07.864286 
; ----------------------------------------
G1 X50.0000 Y50.0000
G1 Z0.2000
; rectangle 10 mm X 40 mm dir: CW start: LL
G1 F1800.00
G1 X50.0000 Y50.0000 E0.0000 ; ext_move 0.0000 mm
G1 X50.0000 Y90.0000 E2.1189 ; ext_move 40.0000 mm
G1 X60.0000 Y90.0000 E0.5297 ; ext_move 10.0000 mm
G1 X60.0000 Y50.0000 E2.1189 ; ext_move 40.0000 mm
G1 X50.0000 Y50.0000 E0.5297 ; ext_move 10.0000 mm
`

As you can see there is no heater code, only movement and extrusion.

If i send this file to your viewer, it show only the "vertical" lines,  from what i could guess the different colors are for the "milling direction". but the problem is that no horizontal lines are displayed.

I know that it is not a "complete" file but in another viewer, the gcode path is displayed correctly.

TIA and Regards

Carlo D.

**Comment by onekk** [comment]
```
; Created by fdmcode
; File   : ./file.gcode 
; Date   : 2020-05-20 15:09:15.403393 
; ----------------------------------------
G0 X50.0000 Y50.0000 Z0.2000
; abs rect 10 mm X 40 mm dir: CW start: UR
; start point X: 50.0 Y: 50.0 Z: 0.2
G1 F1800.00
G0 X60.0000 Y90.0000
G1 X60.0000 Y50.0000 E2.1189 ; ext_move 40.0000 mm
G1 X50.0000 Y50.0000 E0.5297 ; ext_move 10.0000 mm
G1 X50.0000 Y90.0000 E2.1189 ; ext_move 40.0000 mm
G1 X60.0000 Y90.0000 E0.5297 ; ext_move 10.0000 mm
G0 X50.0000 Y50.0000
```

This lead to this error:

```
Gcode Reader
1. Line segments information: 
count     2.0
mean      inf
std       NaN
min      40.0
25%       inf
50%       inf
75%       inf
max       inf
dtype: float64
2. Number of layers: 0
Traceback (most recent call last):
  File "/home/common/Remote/3d_print/gcodegen/Gcode-Reader/src/gcode_reader.py", line 1032, in <module>
    command_line_runner()
  File "/home/common/Remote/3d_print/gcodegen/Gcode-Reader/src/gcode_reader.py", line 966, in command_line_runner
    gcode_reader.describe()
  File "/home/common/Remote/3d_print/gcodegen/Gcode-Reader/src/gcode_reader.py", line 806, in describe
    assert(len(self.seg_index_bars) == len(self.subpath_index_bars))
AssertionError

```

Maybe the gcode generated is not "correct" but as said if i import it in a CAM program it visualize the path without complain.

Hope it helps

Regards

Carlo D.

**Comment by zhangyaqi1989** [comment]
Thanks. Your G-Code is valid. It turns out yesterday I did not really fix the bug. Now it should work.

**Comment by onekk** [comment]
Thanks, but it seems that the new code is not plotting the figure.

I have downloaded only the gcode_reader.py in src directory as it seems the only file changed, due to bandwidth limitation, i prefer to download only the relevant files.

Maybe is something related to the external library versions, I'm using arch Linux (really is Artix Linux) that is relative bleeding edge as library versions.

If you want some infos about versions of my installed library, feel free to ask.

If I can I will be happy to help.

Sadly in your file I can't find version information, that could help to check it the code is correct.

Could you kindly explain me the path color?

I've noted that seems that G0 move (or generally not extruding moves) are not plotted.

There is a manner to display these move, maybe with a different color, like in others programs, that use dashed lines for "rapid" (G0) moves.

I want not bother you, only suggesting things.

However thanks for your work.

Best Regards

Carlo D.

**Comment by zhangyaqi1989** [comment]
It works on my laptop. 
The python version is 3.7.3. 
numpy version is 1.18.1. 
matplotlib version is 3.1.3. 
pandas version is 1.0.1.
seaborn version is 0.10.0.
Color has no meaning (it is picked by matplotlib, I did not set color).
If you want to use single color, you can change the SINGLE_COLOR to True on Line P51. 
G0 command is not plotted. I will consider your suggestions. Thanks.

**Comment by onekk** [comment]
here thge result of this code inserted in gcode_reader.py

It's a nightmare to find out the syntax for each library to obtain the version number, luckily I'm using Spyder IDe with a decent introspection for the imported libraries. :-D

```
def print_ver():
    import matplotlib as mpl
    import platform
    print("python      : ", platform.python_version())
    print("numpy       : ", np.version.full_version)
    print ("matplotlib :", mpl.__version__)
    print("pandas      : ", pd._version.get_versions()["version"])
    print("seaborn     : ", sns.__version__)

```
python   :  3.8.3
numpy    :  1.18.4
matplotlib : 3.1.3
pandas   :  1.0.3
seaborn  :  0.10.0

Hope it helps

Many thanks.

Regards

Carlo D.
